In [2]:
import numpy as np

In [5]:
np.__version__

'1.14.0'

In [6]:
import array

In [8]:
arr = array.array("i", [i for i in range(100)])

In [9]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
### numpy.array

In [13]:
nparr = np.array([i for i in range(10)])


In [14]:
nparr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5] = 'machine learning'

ValueError: invalid literal for int() with base 10: 'machine learning'

In [16]:
nparr[5] = 100

In [17]:
nparr


array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [18]:
nparr.dtype

dtype('int32')

In [19]:
nparr[5] = 5.0

In [20]:
nparr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr[5] = 3.2

In [22]:
nparr


array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [23]:
nparr[3] = 3.14

In [24]:
nparr


array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [25]:
nparr.dtype

dtype('int32')

In [26]:
### Numpy

In [27]:
### Numpy


In [28]:
nparr = np.array([1,2,3.14
                 ])

In [29]:
nparr


array([1.  , 2.  , 3.14])

In [30]:
nparr.dtype


dtype('float64')

In [36]:
# 其他创建nump.array 的方法
### 下面来介绍

In [37]:
### 其他创建

In [38]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.ones((3,5,1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [41]:
np.full(shape=(3, 5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [42]:
np.arrange(0,20,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [44]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [49]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
np.random.randint(4, 8, 10)

array([6, 7, 4, 6, 4, 6, 5, 7, 7, 4])

In [51]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 5, 6, 5, 6],
       [6, 6, 7, 4, 6],
       [5, 7, 6, 6, 7]])

In [55]:
np.random.seed(666) ## explictly set the seed for a shareable code

In [57]:
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 7, 4],
       [6, 4, 7, 5, 6],
       [4, 7, 5, 5, 5]])

In [65]:
np.random.randint(0,10,1)

array([0])