## 05 Numpy.array的基本操作

In [ ]:
import numpy as np

In [9]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [11]:
x.ndim

1

In [12]:
x.shape

(10,)

In [14]:
X.size

15

### numpy.array的数据访问

In [15]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[0]

0

In [17]:
x[-1]

9

In [18]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
X[0][0]

0

In [21]:
X[(0,0)]

0

In [22]:
X[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
x[:5]

array([0, 1, 2, 3, 4])

In [24]:
x[5:]

array([5, 6, 7, 8, 9])

In [25]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [28]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [30]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [31]:
X[0, :]

array([0, 1, 2, 3, 4])

In [35]:
X[0, :].ndim

1

In [38]:
X[:, 0]

array([ 0,  5, 10])

In [39]:
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [43]:
subX[0, 0] = 100
subX


array([[100,   1,   2],
       [  5,   6,   7]])

In [44]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [45]:
x.shape

(10,)

In [46]:
x.ndim

1

In [47]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
B = x.reshape(1, 10)

In [50]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
B.ndim

2

In [52]:
B.shape

(1, 10)

In [53]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
x.reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [57]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [58]:
x.reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [59]:
x.ndim

1

### 合并操作

In [60]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [61]:
x

array([1, 2, 3])

In [62]:
y

array([3, 2, 1])

In [63]:
help(np.concatenate)

Help on built-in function concatenate in module numpy.core.multiarray:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
                  near-equal size.
  

In [64]:
z = np.array([666,666,666])

In [65]:
np.concatenate(x, y, z)

TypeError: only integer scalar arrays can be converted to a scalar index

In [66]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [67]:
A = np.array([[1,2,3],[4, 5,6]])

In [68]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [70]:
np.hstack([A, B])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [71]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [73]:
np.hstack([A, B])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [74]:
B = np.full((2, 2), 100)

In [75]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [76]:
help(np.hstack)

Help on function hstack in module numpy.core.shape_base:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
 

### 数据分割

In [77]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.split(x, [3, 7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [79]:
help(np.split
    )

Help on function split in module numpy.lib.shape_base:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arrays : list of nd

In [81]:
A = np.arange(16).reshape((4,4))

In [82]:
A1, A2 = np.split(A, [2])

In [83]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [84]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
A1, A2 = np.split(A, [2], axis=1)

In [86]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [87]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [88]:
upper, slower = np.vsplit(A,[2])

In [89]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [90]:
slower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
left, right = np.hsplit(A, [2])

In [92]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [93]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [94]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
X, y = np.hsplit(data, [-1])

In [96]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [97]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [98]:
y[:, 0]

array([ 3,  7, 11, 15])

In [99]:
n = 1000000
L = [i for i in range(n)]

In [100]:
%%time
A = []
for e in L:
    A.append(2*e)

Wall time: 194 ms


In [101]:
%%timeit
A = []
for e in L:
    A.append(2*e)

152 ms ± 3.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [102]:
%%time
A = np.array(2*e for e in L)

Wall time: 21.1 ms


In [103]:
%%time
A = 2 * L

Wall time: 20.6 ms


In [104]:
L = np.arange(n)

In [105]:
%%time
A = 2*L

Wall time: 24.1 ms


In [106]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [107]:
n = 10
L = np.arange(n)
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])