### Scikit-learn中的Scalar

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X[:10, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=666)

### scikit-learn 中的standardScalar

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
standardScaler = StandardScaler()

In [15]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [16]:
standardScaler.mean_

array([5.83416667, 3.0825    , 3.70916667, 1.16916667])

In [18]:
standardScaler.scale_

array([0.81019502, 0.44076874, 1.76295187, 0.75429833])

In [19]:
standardScaler.transform(X_train)

array([[-0.90616043,  0.94720873, -1.30982967, -1.28485856],
       [-1.15301457, -0.18717298, -1.30982967, -1.28485856],
       [-0.16559799, -0.64092567,  0.22169257,  0.17345038],
       [ 0.45153738,  0.72033239,  0.95909217,  1.49918578],
       [-0.90616043, -1.3215547 , -0.40226093, -0.0916967 ],
       [ 1.43895396,  0.2665797 ,  0.56203085,  0.30602392],
       [ 0.3281103 , -1.09467835,  1.07253826,  0.30602392],
       [ 2.1795164 , -0.18717298,  1.63976872,  1.2340387 ],
       [-0.78273335,  2.30846679, -1.25310662, -1.4174321 ],
       [ 0.45153738, -2.00218372,  0.44858475,  0.43859746],
       [ 1.80923518, -0.41404933,  1.46959958,  0.83631808],
       [ 0.69839152,  0.2665797 ,  0.90236912,  1.49918578],
       [ 0.20468323,  0.72033239,  0.44858475,  0.571171  ],
       [-0.78273335, -0.86780201,  0.10824648,  0.30602392],
       [-0.53587921,  1.40096142, -1.25310662, -1.28485856],
       [-0.65930628,  1.40096142, -1.25310662, -1.28485856],
       [-1.0295875 ,  0.

In [25]:
X_train = standardScaler.transform(X_train)

In [26]:
X_train

array([[-0.90616043,  0.94720873, -1.30982967, -1.28485856],
       [-1.15301457, -0.18717298, -1.30982967, -1.28485856],
       [-0.16559799, -0.64092567,  0.22169257,  0.17345038],
       [ 0.45153738,  0.72033239,  0.95909217,  1.49918578],
       [-0.90616043, -1.3215547 , -0.40226093, -0.0916967 ],
       [ 1.43895396,  0.2665797 ,  0.56203085,  0.30602392],
       [ 0.3281103 , -1.09467835,  1.07253826,  0.30602392],
       [ 2.1795164 , -0.18717298,  1.63976872,  1.2340387 ],
       [-0.78273335,  2.30846679, -1.25310662, -1.4174321 ],
       [ 0.45153738, -2.00218372,  0.44858475,  0.43859746],
       [ 1.80923518, -0.41404933,  1.46959958,  0.83631808],
       [ 0.69839152,  0.2665797 ,  0.90236912,  1.49918578],
       [ 0.20468323,  0.72033239,  0.44858475,  0.571171  ],
       [-0.78273335, -0.86780201,  0.10824648,  0.30602392],
       [-0.53587921,  1.40096142, -1.25310662, -1.28485856],
       [-0.65930628,  1.40096142, -1.25310662, -1.28485856],
       [-1.0295875 ,  0.

In [27]:
X_test_standard = standardScaler.transform(X_test)

In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [32]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [33]:
knn_clf.score(X_test_standard, y_test)

1.0

In [1]:
knn_clf.score()

NameError: name 'knn_clf' is not defined

### MinMaxScaler

In [2]:
from sklearn import datasets

In [3]:
import numpy as np

In [4]:
iris = datasets.load_iris()

In [5]:
iris[:10]

TypeError: unhashable type: 'slice'

In [6]:
iris[:10, :]

TypeError: unhashable type: 'slice'

In [7]:
X = iris.data
y = iris.target

In [8]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [9]:
X[:10, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [10]:
X[:10, :2]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

In [11]:
y.shape

(150,)

In [12]:
X.shape

(150, 4)

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
min_max_scaler = MinMaxScaler()

In [15]:
from sklearn.modelSelection import train_test_split

ModuleNotFoundError: No module named 'sklearn.modelSelection'

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_ratio=0.2, random_state=666)

TypeError: Invalid parameters passed: {'test_ratio': 0.2}

In [18]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=666)

In [19]:
min_max_scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [20]:
X_test_std = min_max_scaler.transform(X_test)

In [21]:
X_test_std[:10]

array([[0.36111111, 0.41666667, 0.60714286, 0.58333333],
       [0.41666667, 0.33333333, 0.71428571, 0.95833333],
       [0.19444444, 0.125     , 0.39285714, 0.375     ],
       [0.41666667, 0.29166667, 0.71428571, 0.75      ],
       [0.08333333, 0.45833333, 0.07142857, 0.04166667],
       [0.33333333, 0.20833333, 0.51785714, 0.5       ],
       [0.38888889, 0.33333333, 0.60714286, 0.5       ],
       [0.61111111, 0.41666667, 0.73214286, 0.79166667],
       [0.55555556, 0.125     , 0.58928571, 0.5       ],
       [0.33333333, 0.25      , 0.58928571, 0.45833333]])

In [22]:
import matplotlib
import matplotlib.pyplot as plt

In [25]:
X_test_std.shape

(30, 4)

In [27]:
y_test

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
X_train_std = min_max_scaler.transform(X_train)

In [31]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [33]:
knn_clf.fit(X_train_std, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [35]:
y_predict = knn_clf.predict(X_test_std)

In [36]:
sum(y_predict == y_test)

30

In [37]:
sum(y_predict == y_test) / y_test

C:\Users\xliu\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([30., 15., 30., 15., inf, 30., 30., 15., 30., 30., 30., inf, inf,
       inf, 15., 30., inf, 15., 15., 15., 30., inf, 15., inf, 30., 30.,
       inf, 30., 15., 15.])