### 测试我们的算法

In [33]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
X.shape

(150, 4)

In [8]:
y.shape

(150,)

### train_test_split

In [9]:
shuffle_indexes = np.random.permutation(len(X))
shuffle_indexes

array([ 85,  95,  56,  79, 104,  59,  16,  78,  50,  28,  67, 126, 125,
       105,  21, 142,  48,  61,  11, 148,  14,  73,  24, 134, 107,  42,
        23, 137, 146, 138,  99,  43, 101,  38,  64, 129,  62, 102,   4,
        46,  82, 120,  33, 114,  35, 141,  92,  96,  13,  29,  60,  57,
        25, 140,  51,  69, 139,  75,   8,  91, 108,  55,  81,  40,  86,
        22, 116, 121,   9, 109, 112,  27, 119, 136,  12,  47,  26,  74,
       132,  88,  72, 122,  80,  36,  30, 128,   7,  98, 123,  76, 100,
        19,  34,   3,  15,  94,  84,  44,  77,   6,   2,  52,  18,  39,
       149,  20,  87,  10, 124, 145, 110, 133,  93,  83,  45,   0, 106,
        63, 111, 127, 147, 144, 118,  68,  66,   1,  54,  49,  17,  90,
        31, 130,  71, 117,   5,  70, 115, 131,  32,  41,  89,  58,  53,
        97, 113, 135,  37, 103, 143,  65])

In [10]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [11]:
test_size

30

In [12]:
test_indexes = shuffle_indexes[:test_size]

In [13]:
train_indexes = shuffle_indexes[test_size:]

In [16]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [18]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


### Using our algorithm Model-selection

In [20]:
from playML.model_selecction import train_test_split

ModuleNotFoundError: No module named 'playML'

In [21]:
 %run playML


ERROR:root:File `'playML.py'` not found.


In [4]:
from playML_kNN import model_selection

SyntaxError: invalid syntax (<ipython-input-4-8c369b28e738>, line 1)

In [34]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [35]:
from playML_kNN import model_selection

In [36]:
X.shape

(150, 4)

In [37]:
X_train, y_train, X_test, y_test = model_selection.train_test_split(X, y, split_ratio=0.2)

In [12]:
X_train.shape

(120, 4)

In [82]:
from playML_kNN import kNN
my_knn_clf = kNN.KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [83]:
my_knn_clf.predict(X_test)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [88]:
my_knn_clf.predict(X_test)

TypeError: 'builtin_function_or_method' object is not subscriptable