### 实现多元线性回归模型

In [1]:
%run directory_connector.py

In [2]:
import playML_Linear

In [21]:
from playML_Linear import LinearRegression

In [12]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [13]:
boston = datasets.load_boston()
X = boston.data
y = boston.target

In [5]:
X = X[y < 50]
y = y[y < 50]

In [12]:
X.shape

(490, 13)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [7]:
from playML_Linear.LinearRegression import LinearRegression
reg = LinearRegression()
reg.fit_normal(X_train, y_train)

In [62]:
X_b = np.hstack([np.ones((len(X_train), 1)), X_train])
X_b.T.dot(X_b)

array([[3.67000000e+02, 1.27841285e+03, 4.09050000e+03, 4.11486000e+03,
        1.90000000e+01, 2.03220800e+02, 2.28588500e+03, 2.47827000e+04,
        1.40971580e+03, 3.41300000e+03, 1.49189000e+05, 6.78970000e+03,
        1.30886620e+05, 4.75938000e+03],
       [1.27841285e+03, 3.20735431e+04, 3.30089935e+02, 2.27231651e+04,
        2.87969600e+01, 8.58148022e+02, 7.58760050e+03, 1.17386712e+05,
        2.38715013e+03, 2.87154706e+04, 8.19916499e+05, 2.55015955e+04,
        3.50716258e+05, 2.65175320e+04],
       [4.09050000e+03, 3.30089935e+02, 2.41377250e+05, 1.47633950e+04,
        6.00000000e+01, 1.76023750e+03, 2.71626990e+04, 1.39841250e+05,
        2.80926933e+04, 1.61070000e+04, 1.25340550e+06, 6.84901500e+04,
        1.59220583e+06, 2.78107850e+04],
       [4.11486000e+03, 2.27231651e+04, 1.47633950e+04, 6.32249360e+04,
        2.60520000e+02, 2.50315316e+03, 2.49950750e+04, 3.24552248e+05,
        1.19688019e+04, 5.04365200e+04, 1.95996044e+06, 7.80565180e+04,
        1.384

In [53]:
a = np.linalg.inv(X_b.T.dot(X_b))
a

array([[ 1.45683185e+00, -4.56089547e-04, -1.26358478e-04,
         1.10241038e-03,  8.19701975e-03, -6.04252941e-01,
        -8.76320444e-02,  3.21954454e-04, -1.91523065e-02,
         5.62704021e-03, -1.08158965e-04, -2.19832341e-02,
        -2.07720776e-04, -4.56717716e-03],
       [-4.56089547e-04,  6.29068773e-05, -2.41019381e-06,
         3.76199451e-06,  1.05912657e-04,  3.97159450e-04,
         1.77490463e-05,  4.23766665e-07,  4.41741525e-05,
        -3.55910111e-05,  1.30719591e-07,  1.10077358e-06,
         4.05555893e-07, -1.54040251e-05],
       [-1.26358478e-04, -2.41019381e-06,  1.23036455e-05,
         6.63840260e-06,  1.21714074e-05,  4.93693841e-05,
        -5.26012966e-05,  1.16705239e-06, -7.27419074e-05,
         7.75806779e-06, -8.21650187e-07,  3.83622382e-05,
         1.34277644e-09, -1.91858013e-06],
       [ 1.10241038e-03,  3.76199451e-06,  6.63840260e-06,
         2.27094921e-04, -2.28743323e-04, -3.92564858e-03,
         1.36535328e-04,  9.65683497e-07,  1.

In [55]:
b = a.dot(X_b.T)
b

array([[ 3.89655434e-02,  2.90352102e-03,  6.68212369e-02, ...,
        -4.37466622e-02, -5.86605749e-02,  3.14873130e-02],
       [-3.94183727e-05,  5.71483834e-05, -1.84405151e-05, ...,
        -9.06025324e-04, -1.85898317e-04, -4.62990565e-05],
       [-2.88724686e-05, -5.68267618e-05,  2.77177132e-04, ...,
         2.29340223e-05,  4.09351046e-05, -8.71712862e-05],
       ...,
       [-1.48327381e-03, -2.08856789e-03,  4.37051615e-04, ...,
         1.02381174e-03,  1.78150986e-04, -3.30101477e-04],
       [-2.65212835e-07,  4.75741958e-06,  3.60609051e-06, ...,
        -9.83267661e-05,  4.09579871e-05, -1.07806309e-05],
       [-3.60163985e-05, -9.49508340e-05, -3.63373162e-04, ...,
         8.56559564e-04,  4.45885898e-04, -6.10795852e-04]])

In [56]:
b.dot(y_train)

array([ 3.26456608e+01, -1.14235739e-01,  3.12783163e-02, -4.30926281e-02,
       -9.16425531e-02, -1.09940036e+01,  3.49155727e+00, -1.40778005e-02,
       -1.06270960e+00,  2.45307516e-01, -1.23179738e-02, -8.80618320e-01,
        8.43243544e-03, -3.99667727e-01])

In [9]:
reg.score(X_test, y_test)

0.8008916199519345

### kNN Regressor

In [11]:
from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor()
knn_reg.fit(X_train, y_train)
knn_reg.score(X_test, y_test)

0.602674505080953

### 更多有关线性回归的解释

In [16]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets


In [17]:
boston = datasets.load_boston()
X = boston.data
y = boston.target

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [18]:
lin_reg.coef_

array([-1.07170557e-01,  4.63952195e-02,  2.08602395e-02,  2.68856140e+00,
       -1.77957587e+01,  3.80475246e+00,  7.51061703e-04, -1.47575880e+00,
        3.05655038e-01, -1.23293463e-02, -9.53463555e-01,  9.39251272e-03,
       -5.25466633e-01])

In [19]:
np.argsort(lin_reg.coef_)

array([ 4,  7, 10, 12,  0,  9,  6, 11,  2,  1,  8,  3,  5], dtype=int64)

In [21]:
boston.feature_names[np.argsort(lin_reg.coef_)]

array(['NOX', 'DIS', 'PTRATIO', 'LSTAT', 'CRIM', 'TAX', 'AGE', 'B',
       'INDUS', 'ZN', 'RAD', 'CHAS', 'RM'], dtype='<U7')